apiVersion: apps/v1
kind: Deployment
metadata:
  name: contour
  namespace: projectcontour
spec:
  replicas: 2
  selector: { matchLabels: { app: contour } }
  template:
    metadata: { labels: { app: contour } }
    spec:
      serviceAccountName: contour
      containers:
      - name: contour
        image: kuberegistry.dev.kube/rke2/ghcr.io/projectcontour/contour:v1.33.0
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  type: LoadBalancer
  selector: { app: envoy }
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy
  namespace: projectcontour
spec:
  selector: { matchLabels: { app: envoy } }
  template:
    metadata: { labels: { app: envoy } }
    spec:
      containers:
      - name: envoy
        image: kuberegistry.dev.kube/rke2/docker.io/envoyproxy/envoy:v1.34.1
        ports:
        - containerPort: 8080
        - containerPort: 8443