
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool-j64domain
  namespace: metallb-system
spec:
  addresses:
    - 10.0.4.60-10.0.4.69
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv-j64domain
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-pool-j64domain
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool-j64manager
  namespace: metallb-system
spec:
  addresses:
    - 10.0.4.50-10.0.4.59
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv-j64manager
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-pool-j64manager
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool-j52domain
  namespace: metallb-system
spec:
  addresses:
    - 10.0.4.80-10.0.4.89
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv-j52domain
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-pool-j52domain
